spring.application.name=TaskFlowWeb
spring.config.import=optional:classpath:config.yml, optional:classpath:secretkey.yml
application-version: 1.0.0

spring.thymeleaf.cache=false

springdoc.api-docs.path=/api-docs
springdoc.packagesToScan=package1, package2
springdoc.pathsToMatch=/v1, /api/balance/**